version: '2'
services:
    myoffice-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/myOffice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=myOffice
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
